### PR TITLE
add cider nrepl support

### PR DESCRIPTION
**Pull request by peterwang**
the latest version of the cider uses [cider/cider-nrepl "0.8.0-snapshot"], which breaks the nrepl support for lein-ring, this pull request fixes the breakage. to use [cider/cider-nrepl "0.8.0-snapshot"], one has to:

git clone git@github.com:clojure-emacs/cider-nrepl.git
lein install

then introduce it into the project.clj  or ~/.lein/profiles.clj

### CODE REVIEW

**Comment by MichaelBlume** [comment]
Is this still needed? #138 allows configuration of nREPL middleware. Is it also necessary to specify a handler or is middleware enough?

**Comment by MichaelBlume** [comment]
(Also this no longer merges so if it is needed the conflicts should be resolved.)

**Comment by zarkone** [comment]
Yes, i've seen this PR when it wasn't merged, but i didn't make it work with CIDER, don't remeber why.. Will try it again soon for sure and report.

**Comment by MichaelBlume** [comment]
Thanks =)

**Comment by zarkone** [comment]
@MichaelBlume false alarm, It's all working now -- no warnings about unsupported features I had past time, seems like it was my fault. So, CIDER works with https://github.com/weavejester/lein-ring/pull/138

**Comment by MichaelBlume** [comment]
Cool, thanks =)

**Pull request closed without merging**
