### PR TITLE
Use newer version of core.unify -- fix lein-ring with Clojure 1.10

### LINKED ISSUE #203: Dependency `unify` broken with Clojure 1.10
lein-ring 0.12.4 
leinjacker 0.4.2
org.clojure/core.contracts 0.0.1
org.clojure/core.unify 0.5.3

This version of unify has a documented bug with clojure Spec: https://github.com/clojure/core.unify/commit/a5f60d74e1df61291535be43dab7bd2f2eaceb32

The result of this bug in my environment (leiningen 2.9.0 -> clojure 1.10.0 !!!!) is that lein-ring can't start.

### PR DESCRIPTION
**Pull request by camsaul**
Fixes #203

### CODE REVIEW

**Comment by camsaul** [comment]
As mentioned in #203 the problem is actually with `leinjacker` using an outdated `core.unify` dependency so I'll send a PR their way too and reference here and once that gets updated you can take out the  changes here and just bump the `leinjacker` dep instead

**Comment by weavejester** [comment]
Thanks. Can you remove the comment (since we can always see why the change was implemented using `git blame`), and change the commit message to:

    Add core.unify dependency to fix Leinjacker bug

    Fixes #203.

**Comment by camsaul** [comment]
yup. No prob

**Comment by camsaul** [comment]
done

**Pull request merged**
