### PR TITLE
Add option to create exploded war files

### PR DESCRIPTION
**Pull request by mbjarland**
This is useful in situations like gcloud app engine standard environment where exploded is a requirement. 

Tried to be as unintrusive as I could with the code.

### CODE REVIEW

**Comment by MichaelBlume** [comment]
This looks reasonable to me.

**Comment by weavejester** [comment]
This seems fine to me too, but please can you change your commit messages to use the imperative mood, e.g. "Add" instead of "Adding". The commit history is easier to read if it's consistent.

Can you also remove the project version number change from your commits, and squash your commits down so that your typo correction and reformatting commits are removed - they're not ultimately relevant to the commit history.

**Comment by mbjarland** [comment]
Done - commits squashed and project version change reverted.

**Comment by MichaelBlume** [comment]
Thanks =)

**Comment by mbjarland** [comment]
Any ballpark guess on when a potential release with this pr included might get deployed?

**Comment by MichaelBlume** [comment]
I'll aim for before the end of the week?

**Comment by MichaelBlume** [comment]
Done

**Comment by mbjarland** [comment]
Many thanks! Deployments to gcloud std environment just got a lot easier. 

In the parallel universe where i have spare time, I'll try to publish an example project showcasing the mechanics of deploying to both the standard and the flex environments on gcloud. There are enough intricacies that I think quite a few dev just walk away before actually getting things working. 

Anyway, thanks again for the fast turn around.

**Comment by MichaelBlume** [comment]
That'd be exciting!

**Pull request merged**
